---
- name: Check apache2 service 
  hosts: all
  gather_facts: false

  tasks:
  - name: Remove apache2
    apt:
      name: apache2
      state: absent
  - name: Check nginx service
    service:
      name: nginx
      enabled: yes




