---
- name: Check system uptime 
  hosts: localhost
  gather_facts: true

  tasks:
  - name: Check local system uptime
    debug: 
    msg: 
    - "{{ ansible_hostname }}"
    - "{{ ansible_default_ipv4.address }}"

    

